### ISSUE TITLE
Unsupported SOCKS version: 67 / Create HTTP(s) Proxy

### ISSUE THREAD

**Issue by andre-paulo98** [mistakster/throttle-proxy#24]
I found some applications that don't seem to support SOCKS proxy: Jetbrains Toolbox
This is the error that I get:
```
  throttle-proxy:server connection +21s
  throttle-proxy:server connection +1ms
  throttle-proxy:server connection +3ms
  throttle-proxy:server Error: Unsupported SOCKS version: 67
  throttle-proxy:server     at Socket.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\throttle-proxy\node_modules\socks-handler\lib\index.js:19:20)
  throttle-proxy:server     at Object.onceWrapper (events.js:422:26)
  throttle-proxy:server     at Socket.emit (events.js:315:20)
  throttle-proxy:server     at addChunk (_stream_readable.js:295:12)
  throttle-proxy:server     at readableAddChunk (_stream_readable.js:271:9)
  throttle-proxy:server     at Socket.Readable.push (_stream_readable.js:212:10)
  throttle-proxy:server     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) +6ms
  throttle-proxy:server Error: Unsupported SOCKS version: 67
  throttle-proxy:server     at Socket.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\throttle-proxy\node_modules\socks-handler\lib\index.js:19:20)
  throttle-proxy:server     at Object.onceWrapper (events.js:422:26)
  throttle-proxy:server     at Socket.emit (events.js:315:20)
  throttle-proxy:server     at addChunk (_stream_readable.js:295:12)
  throttle-proxy:server     at readableAddChunk (_stream_readable.js:271:9)
  throttle-proxy:server     at Socket.Readable.push (_stream_readable.js:212:10)
  throttle-proxy:server     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) +2ms
  throttle-proxy:server Error: Unsupported SOCKS version: 67
  throttle-proxy:server     at Socket.<anonymous> (C:\Users\andre\AppData\Roaming\npm\node_modules\throttle-proxy\node_modules\socks-handler\lib\index.js:19:20)
  throttle-proxy:server     at Object.onceWrapper (events.js:422:26)
  throttle-proxy:server     at Socket.emit (events.js:315:20)
  throttle-proxy:server     at addChunk (_stream_readable.js:295:12)
  throttle-proxy:server     at readableAddChunk (_stream_readable.js:271:9)
  throttle-proxy:server     at Socket.Readable.push (_stream_readable.js:212:10)
  throttle-proxy:server     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) +1ms
```
These are the settings I have: 
![image](https://user-images.githubusercontent.com/19685105/85227263-4cbb3f80-b3d4-11ea-8638-bdab045e6169.png)

I saw a couple issues mentioning HTTP(s) proxy but they included a branch that is now deleted.

Is there anyway to create a HTTP(s) proxy instead of SOCKS to temporary solve this issue?

**Comment by mistakster** [comment]
Hi André! Thanks for the report. This error happens inside the 3rd party module — [socks-handler](https://github.com/alexkirsz/socks-handler), which handles network communications. I suppose it will be impossible to fix the issue for me without coping all the code from that module.

I can only advice look into the following thread related to the error you've got — https://github.com/alexkirsz/dispatch-proxy/issues/63

**Comment by andre-paulo98** [comment]
Alright I'll do thank you!
